// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ru5awNtxTlm-azVYoGPfEyALyl6A7xk',
    appId: '1:371612928768:web:6e54f13559e045a13141e5',
    messagingSenderId: '371612928768',
    projectId: 'fir-image-bf203',
    authDomain: 'fir-image-bf203.firebaseapp.com',
    storageBucket: 'fir-image-bf203.appspot.com',
    measurementId: 'G-YLHSMV2KQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5VwgHBPwAkYjxxyhvQEwmptv6lX6fZM',
    appId: '1:371612928768:android:d94050683e5ea63d3141e5',
    messagingSenderId: '371612928768',
    projectId: 'fir-image-bf203',
    storageBucket: 'fir-image-bf203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhECQktN686VEN5k1mdlu4S88F702ryCE',
    appId: '1:371612928768:ios:0033c4a8fd58e8483141e5',
    messagingSenderId: '371612928768',
    projectId: 'fir-image-bf203',
    storageBucket: 'fir-image-bf203.appspot.com',
    iosBundleId: 'com.example.firebaseimage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhECQktN686VEN5k1mdlu4S88F702ryCE',
    appId: '1:371612928768:ios:0033c4a8fd58e8483141e5',
    messagingSenderId: '371612928768',
    projectId: 'fir-image-bf203',
    storageBucket: 'fir-image-bf203.appspot.com',
    iosBundleId: 'com.example.firebaseimage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ru5awNtxTlm-azVYoGPfEyALyl6A7xk',
    appId: '1:371612928768:web:3da74e29080806d73141e5',
    messagingSenderId: '371612928768',
    projectId: 'fir-image-bf203',
    authDomain: 'fir-image-bf203.firebaseapp.com',
    storageBucket: 'fir-image-bf203.appspot.com',
    measurementId: 'G-4SHZ7RKK34',
  );
}
